<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="/static/bootstrap-3.3.0/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/css/signin.css" />

    <script type="text/javascript" src="/static/react/0.13.3/react.js"></script>
    <script type="text/javascript" src="/static/react/0.13.3/JSXTransformer.js"></script>

    <script type="text/javascript" src="/static/react-bootstrap/0.24.3/react-bootstrap.js"></script>
</head>
<body>
<?php echo $this->content;?>
</body>
</html>
