<!doctype html>
<html>
<head>
    <title>markdown</title>
</head>
<body>
<div></div>
<div>
    <div style="float: left; width: 16%;">
        <ul>
            <li><a href="/markdown?md=php-jsonrpc">php-jsonrpc</a></li>
            <li><a href="/markdown?md=php-yajl">php-yajl</a></li>
        </ul>
    </div>
    <div style="float: left; width: 64%;">
        <?php echo $this->content;?>
    </div>
</div>
<div style="clear: both;"></div>
</body>
</html>