<!doctype html>
<html>
<head>
    <title>markdown</title>
    <link rel="stylesheet" href="/static/css/github-markdown.css">
    <style>
        .markdown-body {
            box-sizing: border-box;
            min-width: 200px;
            max-width: 980px;
            margin: 0 auto;
            padding: 45px;
        }
    </style>
</head>
<body>
<article class="markdown-body">
<div></div>
<div>
    <div style="float: left; width: 16%;">
        <ul>
            <li><a href="/markdown?md=php-jsonrpc">php-jsonrpc</a></li>
            <li><a href="/markdown?md=php-yajl">php-yajl</a></li>
            <li><a href="/markdown?md=php-cjson">php-cjson</a></li>
        </ul>
    </div>
    <div style="float: left; width: 74%;">
        <?php echo $this->content;?>
    </div>
</div>
<div style="clear: both;"></div>
</article>
</body>
</html>