<!DOCTYPE html>
<html>
<head>
    <title><?php #echo $this->layout['meta_title'];?></title>

    <link rel="stylesheet" href="/static/bootstrap-3.3.0/css/bootstrap.css" />
    <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="/static/react/0.13.3/react.js"></script>
    <script type="text/javascript" src="/static/react/0.13.3/JSXTransformer.js"></script>

    <script type="text/javascript" src="/static/react-bootstrap/0.24.3/react-bootstrap.js"></script>
</head>
<body>
layout
<?php
echo $this->content;
?>
</body>
</html>